-- Phase 5.2
-- Repair auto-generated integer primary keys for Phase 5 remediation tables.
--
-- Phase 5.1 created several primary-key columns as plain INTEGER PRIMARY KEY.
-- SQLAlchemy expects these integer primary keys to be generated by PostgreSQL.
--
-- This migration is additive and safe for existing rows. Each sequence is
-- advanced to MAX(id) + 1 before becoming the column default.

BEGIN;

-- -------------------------------------------------------------------------
-- remediation_approvals
-- -------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS remediation_approvals_id_seq;

SELECT setval(
    'remediation_approvals_id_seq',
    COALESCE(
        (SELECT MAX(id) FROM remediation_approvals),
        0
    ) + 1,
    false
);

ALTER SEQUENCE remediation_approvals_id_seq
    OWNED BY remediation_approvals.id;

ALTER TABLE remediation_approvals
    ALTER COLUMN id
    SET DEFAULT nextval('remediation_approvals_id_seq');


-- -------------------------------------------------------------------------
-- remediation_executions
-- -------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS remediation_executions_id_seq;

SELECT setval(
    'remediation_executions_id_seq',
    COALESCE(
        (SELECT MAX(id) FROM remediation_executions),
        0
    ) + 1,
    false
);

ALTER SEQUENCE remediation_executions_id_seq
    OWNED BY remediation_executions.id;

ALTER TABLE remediation_executions
    ALTER COLUMN id
    SET DEFAULT nextval('remediation_executions_id_seq');


-- -------------------------------------------------------------------------
-- remediation_verifications
-- -------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS remediation_verifications_id_seq;

SELECT setval(
    'remediation_verifications_id_seq',
    COALESCE(
        (SELECT MAX(id) FROM remediation_verifications),
        0
    ) + 1,
    false
);

ALTER SEQUENCE remediation_verifications_id_seq
    OWNED BY remediation_verifications.id;

ALTER TABLE remediation_verifications
    ALTER COLUMN id
    SET DEFAULT nextval('remediation_verifications_id_seq');


-- -------------------------------------------------------------------------
-- remediation_rollbacks
-- -------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS remediation_rollbacks_id_seq;

SELECT setval(
    'remediation_rollbacks_id_seq',
    COALESCE(
        (SELECT MAX(id) FROM remediation_rollbacks),
        0
    ) + 1,
    false
);

ALTER SEQUENCE remediation_rollbacks_id_seq
    OWNED BY remediation_rollbacks.id;

ALTER TABLE remediation_rollbacks
    ALTER COLUMN id
    SET DEFAULT nextval('remediation_rollbacks_id_seq');


-- -------------------------------------------------------------------------
-- remediation_audit_events
-- -------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS remediation_audit_events_id_seq;

SELECT setval(
    'remediation_audit_events_id_seq',
    COALESCE(
        (SELECT MAX(id) FROM remediation_audit_events),
        0
    ) + 1,
    false
);

ALTER SEQUENCE remediation_audit_events_id_seq
    OWNED BY remediation_audit_events.id;

ALTER TABLE remediation_audit_events
    ALTER COLUMN id
    SET DEFAULT nextval('remediation_audit_events_id_seq');


COMMIT;